### ISSUE TITLE
OVH.us api ?

### ISSUE THREAD

**Issue by verylys** [UrielCh/api-ovh-node#3]
Thank you for the excellent tool :)

Any plan to make it work over ovh.us accounts ?

**Comment by UrielCh** [comment]
not relay, I need to choose a new npm name prefix for that.

choosing new name space is the hardest part of the works.

give your naming convention idea :)

**Comment by UrielCh** [comment]
https://www.npmjs.com/search?q=%40ovh-api-us

you have to explicitly give the correct endpoint to the @ovh-api/api to use those API.

**Comment by verylys** [comment]
I was thinking about the ovh-bill-importer tool. Would love to have a "-a" (for --api?) option to select ovh api to query:
ovh-bill-importer -a ovh-us
ovh-bill-importer -a ovh-eu
ovh-bill-importer -a ovh-ca

**Comment by UrielCh** [comment]
without any non FR account I will not be able to test it, but I can implement it.

I will think about it

**Comment by UrielCh** [comment]
Implemented, but not working due to a lake of appKey and appSecret for us and ca.
```
ovh-bill-importer -a us
ovh-bill-importer -a eu
ovh-bill-importer -a ca
```

**Comment by UrielCh** [comment]
please considere providing me 2 keys from
- https://ca.api.ovh.com/createToken/
- https://us.api.ovh.com/createToken/

having:
Script name: ovh-bill-importer
Script description: ovh-bill-importer npm keys
Validity: Unlimited
Rights: 
- GET /me
- GET /me/bill
- GET /me/bill/*

**Comment by UrielCh** [comment]
I have just check:
- https://api.ovh.com/console/
- https://api.us.ovhcloud.com/console/
- https://ca.api.ovh.com/console/

using the same key.
so it may works as it.

can you try the GIT version ?

- clone it
- go to sample/ovh-bill-importer
- run npm install
- run node index.js -a us .....
